# default configuration for every rule (unless overridden)
__default__:
  partition: express
  nodes: 1
  ntasks: 1
  time: 10  # min
  output: "output/marcc_logs/{rule}/slurm-%j.out"
  error: "output/marcc_logs/{rule}/slurm-%j.err"
  job-name: "{rule}"

# configuration for "project_counts" rule -- overrides the default
project_counts:
  time: 15
  ntasks: 2

